### ISSUE TITLE
Does not appear to work with deno 1.7.2 and docker API 1.41

### ISSUE THREAD

**Issue by ioloie** [Oursin/denocker#4]
I'm trying to use this on MacOS (10.14.6) and the following code logs an empty array:

```typescript
// index.ts
import Docker from "https://github.com/Oursin/denocker/raw/main/index.ts";

const docker = new Docker("/var/run/docker.sock");

const containers = await docker.containers.list({ all: true });

console.log(containers);
```

```bash 
# terminal
$ deno run --unstable --allow-all index.ts
> []
```

Strangely, creating a container using the following works as expected :
```typescript
const container = await docker.containers.create("my_container", {
  Image: "alpine",
  Cmd: ["ls"],
  StopTimeout: 10,
});
```

**Note:** I'm currently using `main` to work around #2

**Comment by Oursin** [comment]
Thanks for the report, I could reproduce the bug, I'm working on it :+1:

**Comment by Oursin** [comment]
It should now be fixed in v0.1.1

**Comment by Markcial** [comment]
The change is not reflected on the deno package https://deno.land/x/denocker@v0.1.0/types.ts#L210

**Comment by Oursin** [comment]
Thanks @Markcial, I don't know why deno.land didn't pick the new release, I'll try updating it. In the meantime you can use `https://raw.githubusercontent.com/Oursin/denocker/v0.1.0/index.ts` as an import path.

**Comment by Oursin** [comment]
Just updated the package to v0.2.0 :+1:
